// This file is auto-generated by Lovable. Do not modify it.
// Auth0 is used directly for authentication in this project.

export const lovable = {
  auth: {
    signInWithOAuth: async () => {
      throw new Error("Auth0 is used directly. See useAuth hook.");
    },
  },
};
